language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t paulapufek/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true paulapufek/docker-react npm run test